# Use Homebrew bash (5.x) for plugins that need it
set-environment -g PATH "/usr/local/bin:/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin"

# True color support
set-option -sa terminal-overrides ",xterm*:Tc"

# Start windows and panes at 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Keyboard
set -g mode-keys vi
set -g escape-time 10

# Prefix: C-a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Copy mode
unbind [
bind Escape copy-mode
unbind p
bind p paste-buffer
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection

# Pane resizing
bind -n C-Up resize-pane -U 10
bind -n C-Down resize-pane -D 10
bind -n C-Left resize-pane -L 10
bind -n C-Right resize-pane -R 10

# Mouse
set -g mouse on

# Open panes in CWD
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @vim_navigator_prefix_mapping_clear_screen ""

# Theme
set -g @plugin 'fabioluciano/tmux-tokyo-night'
set -g @powerkit_theme "custom"
set -g @powerkit_custom_theme_path "~/.config/tmux/themes/tomorrow-night-dark.sh"
set -g @powerkit_status_position "bottom"
set -g @powerkit_plugins "git,cwd"



# Initialize TPM (keep at bottom)
run '~/.tmux/plugins/tpm/tpm'
