name: services
root: ~/Code/infl/

windows:
  - hub:
      root: ~/Code/infl/hub
      layout: 73a2,238x53,0,0{180x53,0,0,16,57x53,181,0[57x31,181,0,17,57x21,181,32,18]}
      panes:
        - rvm use 2.4.9; vim
        - rvm use 2.4.9
        - rvm use 2.4.9
  - api:
      root: ~/Code/infl/advocate-api
      layout: 73a2,238x53,0,0{180x53,0,0,16,57x53,181,0[57x31,181,0,17,57x21,181,32,18]}
      panes:
        - vim
        -
        -
  - discourse:
      root: ~/Code/infl/discourse
      layout: 73a2,238x53,0,0{180x53,0,0,16,57x53,181,0[57x31,181,0,17,57x21,181,32,18]}
      panes:
        - vim
        -
        -
